version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${APP_EXPOSED_PORT}:${APP_PORT}
    environment:
      APP_MODE: ${APP_MODE}
      POSTGRES_EXPOSED_PORT: ${POSTGRES_EXPOSED_PORT}
      POSTGRES_HOST: db
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_EXPOSED_PORT}:8080

volumes:
  pgdata: {}
